default_context:
  project_name: 'my-api'
  project_slug: 'my-api'
  domain_main: 'my-api.com'
  domain_staging: 'stag.my-api.com'
  docker_swarm_stack_name_main: 'my-api-com'
  docker_swarm_stack_name_staging: 'stag-my-api-com'
  secret_key: 'uqr3lre74b'
  first_superuser: 'admin'
  first_superuser_password: '2vd5vcd00sji'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.my-api.com", "https://stag.my-api.com", "https://my-api.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@my-api.com'
  postgres_password: 'p1jpuij6ihrz'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: '2vd5vcd00sji'
  traefik_constraint_tag: 'my-api.com'
  traefik_constraint_tag_staging: 'stag.my-api.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:2vd5vcd00sji'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
