"""Change device_data_bind id to uuid type

Revision ID: 3fa0a4910a33
Revises: 5fc1340b821c
Create Date: 2022-09-26 23:33:32.043981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fa0a4910a33'
down_revision = '5fc1340b821c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_data_bind', sa.Column('device_uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('device_data_bind', sa.Column('subscriber_uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_index('ix_device_data_bind_device_id', table_name='device_data_bind')
    op.drop_index('ix_device_data_bind_subscriber_id', table_name='device_data_bind')
    op.create_index(op.f('ix_device_data_bind_device_uuid'), 'device_data_bind', ['device_uuid'], unique=False)
    op.create_index(op.f('ix_device_data_bind_subscriber_uuid'), 'device_data_bind', ['subscriber_uuid'], unique=False)
    op.drop_column('device_data_bind', 'subscriber_id')
    op.drop_column('device_data_bind', 'device_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_data_bind', sa.Column('device_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('device_data_bind', sa.Column('subscriber_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_device_data_bind_subscriber_uuid'), table_name='device_data_bind')
    op.drop_index(op.f('ix_device_data_bind_device_uuid'), table_name='device_data_bind')
    op.create_index('ix_device_data_bind_subscriber_id', 'device_data_bind', ['subscriber_id'], unique=False)
    op.create_index('ix_device_data_bind_device_id', 'device_data_bind', ['device_id'], unique=False)
    op.drop_column('device_data_bind', 'subscriber_uuid')
    op.drop_column('device_data_bind', 'device_uuid')
    # ### end Alembic commands ###
