"""Sensor Location and Sensor Type

Revision ID: 539920b46fb2
Revises: 670fc6cf16d0
Create Date: 2022-08-28 04:07:12.623792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539920b46fb2'
down_revision = '670fc6cf16d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensorlocation',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_sensorlocation_location_id'), 'sensorlocation', ['location_id'], unique=False)
    op.create_table('sensortype',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_index(op.f('ix_sensortype_type_id'), 'sensortype', ['type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensortype_type_id'), table_name='sensortype')
    op.drop_table('sensortype')
    op.drop_index(op.f('ix_sensorlocation_location_id'), table_name='sensorlocation')
    op.drop_table('sensorlocation')
    # ### end Alembic commands ###
