"""Device data bind

Revision ID: 5fc1340b821c
Revises: dd35dde6615c
Create Date: 2022-09-22 01:03:31.290345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc1340b821c'
down_revision = 'dd35dde6615c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_data_bind',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('binder_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('device_id', sa.BIGINT(), nullable=False),
    sa.Column('device_prop', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subscriber_id', sa.BIGINT(), nullable=False),
    sa.Column('char_placeholder', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_data_bind_device_id'), 'device_data_bind', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_data_bind_id'), 'device_data_bind', ['id'], unique=False)
    op.create_index(op.f('ix_device_data_bind_subscriber_id'), 'device_data_bind', ['subscriber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_data_bind_subscriber_id'), table_name='device_data_bind')
    op.drop_index(op.f('ix_device_data_bind_id'), table_name='device_data_bind')
    op.drop_index(op.f('ix_device_data_bind_device_id'), table_name='device_data_bind')
    op.drop_table('device_data_bind')
    # ### end Alembic commands ###
