"""Register Sensor

Revision ID: 670fc6cf16d0
Revises: d4867f3a4c0a
Create Date: 2022-08-28 03:04:58.819378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670fc6cf16d0'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('date_time_index', table_name='message')
    op.create_index(op.f('ix_message_created'), 'message', ['created'], unique=False)
    op.create_index(op.f('ix_message_hum'), 'message', ['hum'], unique=False)
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_index(op.f('ix_message_temp'), 'message', ['temp'], unique=False)
    op.create_index(op.f('ix_sensor_id'), 'sensor', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_id'), table_name='sensor')
    op.drop_index(op.f('ix_message_temp'), table_name='message')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_index(op.f('ix_message_hum'), table_name='message')
    op.drop_index(op.f('ix_message_created'), table_name='message')
    op.create_index('date_time_index', 'message', ['created'], unique=False)
    # ### end Alembic commands ###
