"""Sensor Location and Sensor Type change tables names

Revision ID: 6c6cf9493da5
Revises: 539920b46fb2
Create Date: 2022-08-28 04:15:25.003652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6cf9493da5'
down_revision = '539920b46fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_location',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_sensor_location_location_id'), 'sensor_location', ['location_id'], unique=False)
    op.create_table('sensor_type',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_index(op.f('ix_sensor_type_type_id'), 'sensor_type', ['type_id'], unique=False)
    op.drop_index('ix_sensorlocation_location_id', table_name='sensorlocation')
    op.drop_table('sensorlocation')
    op.drop_index('ix_sensortype_type_id', table_name='sensortype')
    op.drop_table('sensortype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensortype',
    sa.Column('type_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('type_id', name='sensortype_pkey')
    )
    op.create_index('ix_sensortype_type_id', 'sensortype', ['type_id'], unique=False)
    op.create_table('sensorlocation',
    sa.Column('location_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('location_id', name='sensorlocation_pkey')
    )
    op.create_index('ix_sensorlocation_location_id', 'sensorlocation', ['location_id'], unique=False)
    op.drop_index(op.f('ix_sensor_type_type_id'), table_name='sensor_type')
    op.drop_table('sensor_type')
    op.drop_index(op.f('ix_sensor_location_location_id'), table_name='sensor_location')
    op.drop_table('sensor_location')
    # ### end Alembic commands ###
