"""Sensor Type screen options and json settings

Revision ID: dd35dde6615c
Revises: e4491547f477
Create Date: 2022-09-22 00:21:35.020500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd35dde6615c'
down_revision = 'e4491547f477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_type', sa.Column('screen_type', sa.SMALLINT(), nullable=True))
    op.add_column('device_type', sa.Column('json', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_type', 'json')
    op.drop_column('device_type', 'screen_type')
    # ### end Alembic commands ###
