"""static_display_data table

Revision ID: dfa01fc7000f
Revises: 3fa0a4910a33
Create Date: 2022-09-30 00:36:30.806949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfa01fc7000f'
down_revision = '3fa0a4910a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_display_data',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('frame_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('device_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('frame_priority', sa.SMALLINT(), nullable=True),
    sa.Column('data_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_static_display_data_device_uuid'), 'static_display_data', ['device_uuid'], unique=False)
    op.create_index(op.f('ix_static_display_data_id'), 'static_display_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_static_display_data_id'), table_name='static_display_data')
    op.drop_index(op.f('ix_static_display_data_device_uuid'), table_name='static_display_data')
    op.drop_table('static_display_data')
    # ### end Alembic commands ###
